include("C:/Program Files/CMake/share/cmake-4.4/Modules/GoogleTestAddTests.cmake")
gtest_discover_tests_impl(
  TEST_TARGET [==[unit_tests]==]
  TEST_EXECUTABLE [==[C:/Users/shash/OneDrive/Documents/My own AI/Your-OWN-AI/engine/cpp/build_audit/unit_tests.exe]==]
  TEST_EXECUTOR [==[]==]
  TEST_WORKING_DIR [==[C:/Users/shash/OneDrive/Documents/My own AI/Your-OWN-AI/engine/cpp/build_audit]==]
  TEST_EXTRA_ARGS [==[]==]
  TEST_PROPERTIES [==[]==]
  TEST_PREFIX [==[]==]
  TEST_SUFFIX [==[]==]
  TEST_FILTER [==[]==]
  NO_PRETTY_TYPES [==[FALSE]==]
  NO_PRETTY_VALUES [==[FALSE]==]
  TEST_LIST [==[unit_tests_TESTS]==]
  CTEST_FILE [==[C:/Users/shash/OneDrive/Documents/My own AI/Your-OWN-AI/engine/cpp/build_audit/unit_tests_e3b0c442_tests.cmake]==]
  TEST_DISCOVERY_TIMEOUT [==[5]==]
  TEST_DISCOVERY_EXTRA_ARGS [==[]==]
  TEST_XML_OUTPUT_DIR [==[]==]
  TEST_JSON_OUTPUT_DIR [==[C:/Users/shash/OneDrive/Documents/My own AI/Your-OWN-AI/engine/cpp/build_audit]==]
)
