if(EXISTS "C:/Users/shash/OneDrive/Documents/My own AI/Your-OWN-AI/engine/cpp/build_test/unit_tests_e3b0c442_tests.cmake")
  include("C:/Users/shash/OneDrive/Documents/My own AI/Your-OWN-AI/engine/cpp/build_test/unit_tests_e3b0c442_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
